name:  Element.serialize
author:  arieh
current:  1.1
category:  Forms
tags:  [Element,serialize,forms]
#demo:  http://arieh.github.com/Element.serialize
#docs:  http://moodocs.net/arieh/Element.serialize/Element.serialize
